---    
- name: Install httpd (Apache)
  yum:
    name: '{{ package_name }}'
    state: latest

- name: Deploy custom index.html
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
  notify: restart apache

- name: Include firewall role to open specified ports
  include_role:
    name: fedora.linux_system_roles.firewall
  vars:
    firewall:
      - port: '80/tcp'
        state: enabled
        permant: true
